// Demo seed for shipment validation table
export const SHIPMENT_VALIDATION_DATA = [
  {
    id: 1,
    status: 'error',
    recipient: 'Jane Cooper',
    address1: '4517 Washington A',
    city: 'Kentucky',
    state: 'KY',
    zip: 'ABC-123',
    service: 'Standard Ground',
    action: 'Re-validate',
    error: 'Invalid ZIP',
  },
  {
    id: 2,
    status: 'warning',
    recipient: 'Cody Fisher',
    address1: '2118 Thornridge Ci',
    city: 'Syracuse',
    state: 'CT',
    zip: '35624',
    service: 'Express',
    action: 'Re-validate',
    warning: 'Suspicious address',
  },
  {
    id: 3,
    status: 'valid',
    recipient: 'Esther Howard',
    address1: '1901 Thornridge Ci',
    city: 'Shiloh',
    state: 'HI',
    zip: '81063',
    service: 'Priority Mail',
    action: '',
  },
  {
    id: 4,
    status: 'valid',
    recipient: 'Cameron Williamsc',
    address1: '3891 Ranchview Dr',
    city: 'Richardson',
    state: 'CA',
    zip: '62639',
    service: 'Next Day Air',
    action: '',
  },
];
